services:
  tests:
    image: mcr.microsoft.com/dotnet/sdk:8.0-nanoserver-1809
    working_dir: "c:\\src"
    entrypoint:
     - dotnet
    command:
     - test
     - FlacHasher.sln
     - --configuration
     - Release
     - /p:EnableWindowsTargeting=true
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
    volumes:
      - type: bind
        source: .
        target: "c:\\src"