services:
  tests:
    build:
      dockerfile: Dockerfile.lnx
    entrypoint:
     - dotnet
    command:
     - test
     - FlacHasher.sln
     - --configuration
     - Release
     - /p:EnableWindowsTargeting=true
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"